<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MBkSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('m_bahan_kajian')->insert([
            ['bk_id' => 1, 'prodi_id' => 2, 'bk_kategori' => 'BTKat1', 'bk_deskripsi' => 'Konsep Tata Kelola Teknologi Informasi'],
            ['bk_id' => 2, 'prodi_id' => 2, 'bk_kategori' => 'BSKat1', 'bk_deskripsi' => 'Konsep Tata Kelola Teknologi Informasi'],
            ['bk_id' => 3, 'prodi_id' => 2, 'bk_kategori' => 'BTKat2', 'bk_deskripsi' => 'Elemen dan Tujuan Tata Kelola Teknologi Informasi'],
            ['bk_id' => 4, 'prodi_id' => 2, 'bk_kategori' => 'BSKat2', 'bk_deskripsi' => 'Kerangka Kerja dan Standard Tata Kelola'],
            ['bk_id' => 5, 'prodi_id' => 2, 'bk_kategori' => 'BTKat3', 'bk_deskripsi' => 'COBIT and the IT Governance Institute'],
            ['bk_id' => 6, 'prodi_id' => 2, 'bk_kategori' => 'BSKat3', 'bk_deskripsi' => 'ITIL and IT Service Management Guidance'],
            ['bk_id' => 7, 'prodi_id' => 2, 'bk_kategori' => 'BTKat4', 'bk_deskripsi' => 'IT Governance Standards : ISO 9001, 27002, and 38500 '],
            ['bk_id' => 8, 'prodi_id' => 2, 'bk_kategori' => 'BSKat4', 'bk_deskripsi' => 'Memahami dan menetapkan kerangka kerja Tata Kelola Teknologi Informasi'],
            ['bk_id' => 9, 'prodi_id' => 2, 'bk_kategori' => 'BTKat5', 'bk_deskripsi' => 'Penerapa Framework Tata kelola Teknologi Informasi '],
            ['bk_id' => 10, 'prodi_id' => 1, 'bk_kategori' => 'BSKat5', 'bk_deskripsi' => 'Memahami UI pada Unity 3D'],
            ['bk_id' => 11, 'prodi_id' => 1, 'bk_kategori' => 'BSKat6', 'bk_deskripsi' => 'Memahami Core UI'],
            ['bk_id' => 12, 'prodi_id' => 1, 'bk_kategori' => 'BTKat6', 'bk_deskripsi' => 'Memahami Inventory UI'],
            ['bk_id' => 13, 'prodi_id' => 1, 'bk_kategori' => 'BTKat7', 'bk_deskripsi' => 'Memahami setting gerak dan animasi karakter player dalam 2D'],
            ['bk_id' => 14, 'prodi_id' => 1, 'bk_kategori' => 'BSKat7', 'bk_deskripsi' => 'Memahami kamera'],
            ['bk_id' => 15, 'prodi_id' => 1, 'bk_kategori' => 'BTKat8', 'bk_deskripsi' => 'Memahami pengaturan light dan effect'],
            ['bk_id' => 16, 'prodi_id' => 1, 'bk_kategori' => 'BSKat8', 'bk_deskripsi' => 'Memahami light dan effect'],
            ['bk_id' => 17, 'prodi_id' => 1, 'bk_kategori' => 'BTKat9', 'bk_deskripsi' => 'Memahami sound dan animasi game yang digunakan'],
            ['bk_id' => 18, 'prodi_id' => 1, 'bk_kategori' => 'BSKat9', 'bk_deskripsi' => 'Memahami Controlling 3D'],
            ['bk_id' => 19, 'prodi_id' => 2, 'bk_kategori' => 'BTKat10', 'bk_deskripsi' => 'Konsep dasar audit sistem informasi'],
            ['bk_id' => 20, 'prodi_id' => 2, 'bk_kategori' => 'BSKat10', 'bk_deskripsi' => 'Standar dan panduan audit sistem informasi'],
            ['bk_id' => 21, 'prodi_id' => 2, 'bk_kategori' => 'BTKat11', 'bk_deskripsi' => 'Management control framework'],
            ['bk_id' => 22, 'prodi_id' => 2, 'bk_kategori' => 'BSKat11', 'bk_deskripsi' => 'Perencanaan dan manajemen audit sistem informasi'],
            ['bk_id' => 23, 'prodi_id' => 2, 'bk_kategori' => 'BTKat12', 'bk_deskripsi' => 'Pengumpulan dan evaluasi bukti'],
            ['bk_id' => 24, 'prodi_id' => 2, 'bk_kategori' => 'BSKat12', 'bk_deskripsi' => 'IT evaluation, direct, and monitoring'],
            ['bk_id' => 25, 'prodi_id' => 2, 'bk_kategori' => 'BTKat13', 'bk_deskripsi' => 'Auditing IT aligning, planning, dan organization'],
            ['bk_id' => 26, 'prodi_id' => 2, 'bk_kategori' => 'BSKat13', 'bk_deskripsi' => 'Auditing IT build, acquiring, and implementation'],
            ['bk_id' => 27, 'prodi_id' => 2, 'bk_kategori' => 'BTKat14', 'bk_deskripsi' => 'Auditing IT delivery, service, dan suppor'],
            ['bk_id' => 28, 'prodi_id' => 2, 'bk_kategori' => 'BSKat14', 'bk_deskripsi' => 'Auditing IT monitoring, evaluation, and assessmen'],
            ['bk_id' => 29, 'prodi_id' => 2, 'bk_kategori' => 'BTKat15', 'bk_deskripsi' => 'IT Governance'],
            ['bk_id' => 30, 'prodi_id' => 2, 'bk_kategori' => 'BSKat15', 'bk_deskripsi' => 'Audit IT pada domain EDM, APO, DSS, dan MEA.'],
            ['bk_id' => 31, 'prodi_id' => 2, 'bk_kategori' => 'BTKat1', 'bk_deskripsi' => 'Konsep dasar ajaran agama'],
    ['bk_id' => 32, 'prodi_id' => 2, 'bk_kategori' => 'BTKat2', 'bk_deskripsi' => 'Penggunaan bahasa Indonesia secara baik dan benar'],
    ['bk_id' => 33, 'prodi_id' => 2, 'bk_kategori' => 'BTKat3', 'bk_deskripsi' => 'Dasar-dasar bahasa Inggris untuk komunikasi sehari-hari'],
    ['bk_id' => 34, 'prodi_id' => 2, 'bk_kategori' => 'BTKat4', 'bk_deskripsi' => 'Konsep teknologi informasi'],
    ['bk_id' => 35, 'prodi_id' => 2, 'bk_kategori' => 'BTKat5', 'bk_deskripsi' => 'Keterampilan berpikir kritis dan pemecahan masalah'],
    ['bk_id' => 36, 'prodi_id' => 2, 'bk_kategori' => 'BTKat6', 'bk_deskripsi' => 'Dasar-dasar akuntansi, manajemen, dan bisnis'],
    ['bk_id' => 37, 'prodi_id' => 2, 'bk_kategori' => 'BTKat7', 'bk_deskripsi' => 'Konsep matematika dasar'],
    ['bk_id' => 38, 'prodi_id' => 2, 'bk_kategori' => 'BTKat8', 'bk_deskripsi' => 'Dasar-dasar pemrograman'],
    ['bk_id' => 39, 'prodi_id' => 2, 'bk_kategori' => 'BTKat9', 'bk_deskripsi' => 'Praktik dasar-dasar pemrograman'],
    ['bk_id' => 40, 'prodi_id' => 2, 'bk_kategori' => 'BTKat10', 'bk_deskripsi' => 'Konsep kewarganegaraan'],
    ['bk_id' => 41, 'prodi_id' => 2, 'bk_kategori' => 'BTKat11', 'bk_deskripsi' => 'Analisa proses bisnis'],
    ['bk_id' => 42, 'prodi_id' => 2, 'bk_kategori' => 'BTKat12', 'bk_deskripsi' => 'Praktik analisa proses bisnis'],
    ['bk_id' => 43, 'prodi_id' => 2, 'bk_kategori' => 'BTKat13', 'bk_deskripsi' => 'Pengenalan sistem informasi'],
    ['bk_id' => 44, 'prodi_id' => 2, 'bk_kategori' => 'BTKat14', 'bk_deskripsi' => 'Algoritma dan struktur data'],
    ['bk_id' => 45, 'prodi_id' => 2, 'bk_kategori' => 'BTKat15', 'bk_deskripsi' => 'Praktik algoritma dan struktur data'],
    ['bk_id' => 46, 'prodi_id' => 2, 'bk_kategori' => 'BTKat16', 'bk_deskripsi' => 'Konsep basis data'],
    ['bk_id' => 47, 'prodi_id' => 2, 'bk_kategori' => 'BTKat17', 'bk_deskripsi' => 'Praktik basis data'],
    ['bk_id' => 48, 'prodi_id' => 2, 'bk_kategori' => 'BTKat18', 'bk_deskripsi' => 'Konsep matematika lanjutan'],
    ['bk_id' => 49, 'prodi_id' => 2, 'bk_kategori' => 'BTKat19', 'bk_deskripsi' => 'Konsep sistem operasi'],
    ['bk_id' => 50, 'prodi_id' => 2, 'bk_kategori' => 'BTKat20', 'bk_deskripsi' => 'Konsep jaringan komputer'],
    ['bk_id' => 51, 'prodi_id' => 2, 'bk_kategori' => 'BTKat21', 'bk_deskripsi' => 'Praktik jaringan komputer'],
    ['bk_id' => 52, 'prodi_id' => 2, 'bk_kategori' => 'BTKat22', 'bk_deskripsi' => 'Rekayasa perangkat lunak'],
    ['bk_id' => 53, 'prodi_id' => 2, 'bk_kategori' => 'BTKat23', 'bk_deskripsi' => 'Pemrograman berbasis objek'],
    ['bk_id' => 54, 'prodi_id' => 2, 'bk_kategori' => 'BTKat24', 'bk_deskripsi' => 'Praktik pemrograman berbasis objek'],
    ['bk_id' => 55, 'prodi_id' => 2, 'bk_kategori' => 'BTKat25', 'bk_deskripsi' => 'Konsep basis data lanjutan'],
    ['bk_id' => 56, 'prodi_id' => 2, 'bk_kategori' => 'BTKat26', 'bk_deskripsi' => 'Praktik basis data lanjutan'],
    ['bk_id' => 57, 'prodi_id' => 2, 'bk_kategori' => 'BTKat27', 'bk_deskripsi' => 'Pemrograman web'],
    ['bk_id' => 58, 'prodi_id' => 2, 'bk_kategori' => 'BTKat28', 'bk_deskripsi' => 'Konsep Pancasila'],
    ['bk_id' => 59, 'prodi_id' => 2, 'bk_kategori' => 'BTKat29', 'bk_deskripsi' => 'Konsep statistika'],
    ['bk_id' => 60, 'prodi_id' => 2, 'bk_kategori' => 'BTKat30', 'bk_deskripsi' => 'Bahasa Inggris lanjutan'],
    ['bk_id' => 61, 'prodi_id' => 2, 'bk_kategori' => 'BTKat31', 'bk_deskripsi' => 'Praktik workshop'],
    ['bk_id' => 62, 'prodi_id' => 2, 'bk_kategori' => 'BTKat32', 'bk_deskripsi' => 'Konsep data warehouse'],
    ['bk_id' => 63, 'prodi_id' => 2, 'bk_kategori' => 'BTKat33', 'bk_deskripsi' => 'Konsep data mining'],
    ['bk_id' => 64, 'prodi_id' => 2, 'bk_kategori' => 'BTKat34', 'bk_deskripsi' => 'Analisis dan perancangan sistem informasi'],
    ['bk_id' => 65, 'prodi_id' => 2, 'bk_kategori' => 'BTKat35', 'bk_deskripsi' => 'Pemrograman web lanjutan'],
    ['bk_id' => 66, 'prodi_id' => 2, 'bk_kategori' => 'BTKat36', 'bk_deskripsi' => 'Metodologi penelitian'],
    ['bk_id' => 67, 'prodi_id' => 2, 'bk_kategori' => 'BTKat37', 'bk_deskripsi' => 'Manajemen rantai pasok'],
    ['bk_id' => 68, 'prodi_id' => 2, 'bk_kategori' => 'BTKat38', 'bk_deskripsi' => 'Perencanaan sumber daya'],
    ['bk_id' => 69, 'prodi_id' => 2, 'bk_kategori' => 'BTKat39', 'bk_deskripsi' => 'Kecerdasan bisnis'],
    ['bk_id' => 70, 'prodi_id' => 2, 'bk_kategori' => 'BTKat40', 'bk_deskripsi' => 'Penjaminan mutu perangkat lunak'],
    ['bk_id' => 71, 'prodi_id' => 2, 'bk_kategori' => 'BTKat41', 'bk_deskripsi' => 'Pemrograman mobile'],
    ['bk_id' => 72, 'prodi_id' => 2, 'bk_kategori' => 'BTKat42', 'bk_deskripsi' => 'Manajemen proyek sistem informasi'],
    ['bk_id' => 73, 'prodi_id' => 2, 'bk_kategori' => 'BTKat43', 'bk_deskripsi' => 'Keselamatan dan kesehatan kerja'],
    ['bk_id' => 74, 'prodi_id' => 2, 'bk_kategori' => 'BTKat44', 'bk_deskripsi' => 'Manajemen jaringan komputer'],
    ['bk_id' => 75, 'prodi_id' => 2, 'bk_kategori' => 'BTKat45', 'bk_deskripsi' => 'Pengembangan karir'],
    ['bk_id' => 76, 'prodi_id' => 2, 'bk_kategori' => 'BTKat46', 'bk_deskripsi' => 'Etika profesi'],
    ['bk_id' => 77, 'prodi_id' => 2, 'bk_kategori' => 'BTKat47', 'bk_deskripsi' => 'Proyek sistem informasi'],
    ['bk_id' => 78, 'prodi_id' => 2, 'bk_kategori' => 'BTKat48', 'bk_deskripsi' => 'Pemasaran digital'],
    ['bk_id' => 79, 'prodi_id' => 2, 'bk_kategori' => 'BTKat49', 'bk_deskripsi' => 'Manajemen hubungan pelanggan'],
    ['bk_id' => 80, 'prodi_id' => 2, 'bk_kategori' => 'BTKat50', 'bk_deskripsi' => 'Big data'],
    ['bk_id' => 81, 'prodi_id' => 2, 'bk_kategori' => 'BTKat51', 'bk_deskripsi' => 'Praktik kewirausahaan'],
    ['bk_id' => 82, 'prodi_id' => 2, 'bk_kategori' => 'BTKat52', 'bk_deskripsi' => 'Studi kelayakan rencana bisnis'],
    ['bk_id' => 83, 'prodi_id' => 2, 'bk_kategori' => 'BTKat53', 'bk_deskripsi' => 'Konsep produk bisnis'],
    ['bk_id' => 84, 'prodi_id' => 2, 'bk_kategori' => 'BTKat54', 'bk_deskripsi' => 'Manajemen bisnis'],
    ['bk_id' => 85, 'prodi_id' => 2, 'bk_kategori' => 'BTKat55', 'bk_deskripsi' => 'Pemasaran bisnis'],
    ['bk_id' => 86, 'prodi_id' => 2, 'bk_kategori' => 'BTKat56', 'bk_deskripsi' => 'Proyek capstone'],
    ['bk_id' => 87, 'prodi_id' => 2, 'bk_kategori' => 'BTKat57', 'bk_deskripsi' => 'Soft skill/kreativitas dan inovasi TI'],
    ['bk_id' => 88, 'prodi_id' => 2, 'bk_kategori' => 'BTKat58', 'bk_deskripsi' => 'Rekayasa teknologi informasi'],
    ['bk_id' => 89, 'prodi_id' => 2, 'bk_kategori' => 'BTKat59', 'bk_deskripsi' => 'Kegiatan MBKM'],
    ['bk_id' => 90, 'prodi_id' => 2, 'bk_kategori' => 'BTKat60', 'bk_deskripsi' => 'Pengenalakan statistika'],
        ]);
    }
}
