<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TMkBkSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('t_mk_bk')->insert([
            ['mk_bk_id' => 1, 'bk_id' => 1, 'mk_id' => 1],
            ['mk_bk_id' => 2, 'bk_id' => 2, 'mk_id' => 1],
            ['mk_bk_id' => 3, 'bk_id' => 3, 'mk_id' => 1],
            ['mk_bk_id' => 4, 'bk_id' => 4, 'mk_id' => 1],
            ['mk_bk_id' => 5, 'bk_id' => 5, 'mk_id' => 1],
            ['mk_bk_id' => 6, 'bk_id' => 6, 'mk_id' => 1],
            ['mk_bk_id' => 7, 'bk_id' => 7, 'mk_id' => 1],
            ['mk_bk_id' => 8, 'bk_id' => 8, 'mk_id' => 1],
            ['mk_bk_id' => 9, 'bk_id' => 9, 'mk_id' => 1],
            ['mk_bk_id' => 10, 'bk_id' => 10, 'mk_id' => 2],
            ['mk_bk_id' => 11, 'bk_id' => 11, 'mk_id' => 2],
            ['mk_bk_id' => 12, 'bk_id' => 12, 'mk_id' => 2],
            ['mk_bk_id' => 13, 'bk_id' => 13, 'mk_id' => 2],
            ['mk_bk_id' => 14, 'bk_id' => 14, 'mk_id' => 2],
            ['mk_bk_id' => 15, 'bk_id' => 15, 'mk_id' => 2],
            ['mk_bk_id' => 16, 'bk_id' => 16, 'mk_id' => 2],
            ['mk_bk_id' => 17, 'bk_id' => 17, 'mk_id' => 2],
            ['mk_bk_id' => 18, 'bk_id' => 18, 'mk_id' => 2],
            ['mk_bk_id' => 19, 'bk_id' => 19, 'mk_id' => 3],
            ['mk_bk_id' => 20, 'bk_id' => 20, 'mk_id' => 3],
            ['mk_bk_id' => 21, 'bk_id' => 21, 'mk_id' => 3],
            ['mk_bk_id' => 22, 'bk_id' => 22, 'mk_id' => 3],
            ['mk_bk_id' => 23, 'bk_id' => 23, 'mk_id' => 3],
            ['mk_bk_id' => 24, 'bk_id' => 24, 'mk_id' => 3],
            ['mk_bk_id' => 25, 'bk_id' => 25, 'mk_id' => 3],
            ['mk_bk_id' => 26, 'bk_id' => 26, 'mk_id' => 3],
            ['mk_bk_id' => 27, 'bk_id' => 27, 'mk_id' => 3],
            ['mk_bk_id' => 28, 'bk_id' => 28, 'mk_id' => 3],
            ['mk_bk_id' => 29, 'bk_id' => 29, 'mk_id' => 3],
            ['mk_bk_id' => 30, 'bk_id' => 30, 'mk_id' => 3],
            ['mk_bk_id' => 31, 'bk_id' => 31, 'mk_id' => 4],
    ['mk_bk_id' => 32, 'bk_id' => 32, 'mk_id' => 5],
    ['mk_bk_id' => 33, 'bk_id' => 33, 'mk_id' => 6],
    ['mk_bk_id' => 34, 'bk_id' => 34, 'mk_id' => 7],
    ['mk_bk_id' => 35, 'bk_id' => 35, 'mk_id' => 8],
    ['mk_bk_id' => 36, 'bk_id' => 36, 'mk_id' => 9],
    ['mk_bk_id' => 37, 'bk_id' => 37, 'mk_id' => 10],
    ['mk_bk_id' => 38, 'bk_id' => 38, 'mk_id' => 11],
    ['mk_bk_id' => 39, 'bk_id' => 39, 'mk_id' => 12],
    ['mk_bk_id' => 40, 'bk_id' => 40, 'mk_id' => 13],
    ['mk_bk_id' => 41, 'bk_id' => 41, 'mk_id' => 14],
    ['mk_bk_id' => 42, 'bk_id' => 42, 'mk_id' => 15],
    ['mk_bk_id' => 43, 'bk_id' => 43, 'mk_id' => 16],
    ['mk_bk_id' => 44, 'bk_id' => 44, 'mk_id' => 17],
    ['mk_bk_id' => 45, 'bk_id' => 45, 'mk_id' => 18],
    ['mk_bk_id' => 46, 'bk_id' => 46, 'mk_id' => 19],
    ['mk_bk_id' => 47, 'bk_id' => 47, 'mk_id' => 20],
    ['mk_bk_id' => 48, 'bk_id' => 48, 'mk_id' => 21],
    ['mk_bk_id' => 49, 'bk_id' => 49, 'mk_id' => 22],
    ['mk_bk_id' => 50, 'bk_id' => 50, 'mk_id' => 23],
    ['mk_bk_id' => 51, 'bk_id' => 51, 'mk_id' => 24],
    ['mk_bk_id' => 52, 'bk_id' => 52, 'mk_id' => 25],
    ['mk_bk_id' => 53, 'bk_id' => 53, 'mk_id' => 26],
    ['mk_bk_id' => 54, 'bk_id' => 54, 'mk_id' => 27],
    ['mk_bk_id' => 55, 'bk_id' => 55, 'mk_id' => 28],
    ['mk_bk_id' => 56, 'bk_id' => 56, 'mk_id' => 29],
    ['mk_bk_id' => 57, 'bk_id' => 57, 'mk_id' => 30],
    ['mk_bk_id' => 58, 'bk_id' => 58, 'mk_id' => 31],
    ['mk_bk_id' => 59, 'bk_id' => 59, 'mk_id' => 32],
    ['mk_bk_id' => 60, 'bk_id' => 60, 'mk_id' => 33],
    ['mk_bk_id' => 61, 'bk_id' => 61, 'mk_id' => 34],
    ['mk_bk_id' => 62, 'bk_id' => 62, 'mk_id' => 35],
    ['mk_bk_id' => 63, 'bk_id' => 63, 'mk_id' => 36],
    ['mk_bk_id' => 64, 'bk_id' => 64, 'mk_id' => 37],
    ['mk_bk_id' => 65, 'bk_id' => 65, 'mk_id' => 38],
    ['mk_bk_id' => 66, 'bk_id' => 66, 'mk_id' => 39],
    ['mk_bk_id' => 67, 'bk_id' => 67, 'mk_id' => 40],
    ['mk_bk_id' => 68, 'bk_id' => 68, 'mk_id' => 41],
    ['mk_bk_id' => 69, 'bk_id' => 69, 'mk_id' => 42],
    ['mk_bk_id' => 70, 'bk_id' => 70, 'mk_id' => 43],
    ['mk_bk_id' => 71, 'bk_id' => 71, 'mk_id' => 44],
    ['mk_bk_id' => 72, 'bk_id' => 72, 'mk_id' => 45],
    ['mk_bk_id' => 73, 'bk_id' => 73, 'mk_id' => 46],
    ['mk_bk_id' => 74, 'bk_id' => 74, 'mk_id' => 47],
    ['mk_bk_id' => 75, 'bk_id' => 75, 'mk_id' => 48],
    ['mk_bk_id' => 76, 'bk_id' => 76, 'mk_id' => 49],
    ['mk_bk_id' => 77, 'bk_id' => 77, 'mk_id' => 50],
    ['mk_bk_id' => 78, 'bk_id' => 78, 'mk_id' => 51],
    ['mk_bk_id' => 79, 'bk_id' => 79, 'mk_id' => 52],
    ['mk_bk_id' => 80, 'bk_id' => 80, 'mk_id' => 53],
    ['mk_bk_id' => 81, 'bk_id' => 81, 'mk_id' => 54],
    ['mk_bk_id' => 82, 'bk_id' => 82, 'mk_id' => 55],
    ['mk_bk_id' => 83, 'bk_id' => 83, 'mk_id' => 56],
    ['mk_bk_id' => 84, 'bk_id' => 84, 'mk_id' => 57],
    ['mk_bk_id' => 85, 'bk_id' => 85, 'mk_id' => 58],
    ['mk_bk_id' => 86, 'bk_id' => 86, 'mk_id' => 59],
    ['mk_bk_id' => 87, 'bk_id' => 87, 'mk_id' => 60],
    ['mk_bk_id' => 88, 'bk_id' => 88, 'mk_id' => 61],
    ['mk_bk_id' => 89, 'bk_id' => 89, 'mk_id' => 62],
    ['mk_bk_id' => 90, 'bk_id' => 90, 'mk_id' => 63],
        ]);
    }
}
